Creating about section
JakAntoniak/JakAntoniak-HTML-CSS-team-7 pull request #5
Opened 2022-10-13 21:06 UTC by TomGrzybowski

Pull request :)

2022-10-14 19:55 UTC, JakAntoniak approved these changes

2022-10-14 19:55 UTC, JakAntoniak commented on src/sass/main.scss
> +@use "./about";
Kozak, nie mam się do czego przywalić :D

2022-10-15 07:44 UTC, JonaszChudobski requested changes
Oprócz tych dwóch commentów, reszta wydaje się spoko :) Sorry, że się czepiam tych odległości, nie jestem złośliwy z natury :>

2022-10-15 07:44 UTC, JonaszChudobski commented on src/sass/_about.scss
> +    &__img {
Wydaje mi się, że odstęp pomiędzy krówskiem a tekstem powyżej jest zbyt mały. Dałeś gapa 15px i on się zrobił pomiędzy wszystkimi elementami tego bloku, a w figmie pomiędzy imgiem a tekstem jest 26px i teraz brakuje tych 11px, o ile się nie mylę. Może jakiś margin-top by załatwił sprawę :)
Podobna sytuacja zrobiła się pod krową, bo masz tego gapa 15px i margin-bottom 30px, co daje 45px, a odległość w figmie jest 46px, ale tu już bym się chyba czepiał :D

2022-10-15 07:44 UTC, JonaszChudobski commented on src/partials/about.html
> +            Aliquam erat volutpat. Aenean accumsan.</p>
U mnie przeglądarka nie ogarnia tej przerwy, może trzeba by było dodać br na wszelki wypadek?

2022-10-15 09:01 UTC, TomGrzybowski commented on src/partials/about.html
> +            Aliquam erat volutpat. Aenean accumsan.</p>
Zrobione

2022-10-15 09:02 UTC, TomGrzybowski commented on src/sass/_about.scss
> +    &__img {
Zrobione

2022-10-15 18:10 UTC, merged