advantages section
JakAntoniak/JakAntoniak-HTML-CSS-team-7 pull request #6
Opened 2022-10-13 21:17 UTC by monika-czulak

images, scss and partial html finished
added few more variables

2022-10-14 14:26 UTC, JonaszChudobski requested changes
Do poprawienia jedynie odległość wspomniana w komentarzu.

2022-10-14 14:26 UTC, JonaszChudobski commented on src/sass/_advantages.scss
> +  &__text {
Ja dodałbym tu jeszcze height dla tego paragrafu, albo ostatecznie margin-bottom (ale trudniej go obliczyć), ponieważ w makiecie wszystkie te wielkie cyfry Titanem One są oddalone od dolnego lorem ipsum.

2022-10-15 12:19 UTC, JakAntoniak requested changes

2022-10-15 12:19 UTC, JakAntoniak commented on src/sass/_advantages.scss
> +
Brakuje mi kontenera ustawionego na 320px.
Chodzi mi o to, że gdy jesteś w przeglądarce na inspektorze to przy rozszerzaniu mobilki cała Twoja sekcja jest "przyklejona do lewej strony. 
Przy rozszerzaniu ma być na środku :)

2022-10-15 12:19 UTC, JakAntoniak commented on src/index.html
>      <include src="./partials/example.html"></include>
śmiało możesz wyrzucić example :)

2022-10-15 18:58 UTC, merged